analyze: false
batch_size: 64
curriculum_dims_end: 28
curriculum_dims_inc: 1
curriculum_dims_interval: 2000
curriculum_dims_start: 28
curriculum_points_end: 40
curriculum_points_inc: 5
curriculum_points_interval: 2000
curriculum_points_start: 40
data: boolean
delete: true
entity: name
family: san
freeze: 0
gpu: 1
keep_every_steps: 100000
learning_rate: 0.0001
llama_weights_path: /home/
log_every_steps: 100
model_name: gpt2
n_dims: 28
n_embd: 256
n_head: 8
n_layer: 12
n_positions: 150
name: test_san_abad845f
nn_score_bsize: 100
nn_score_eval: false
nn_score_n_points: 80
nn_score_num_neighbours: 1
nn_score_start_point: 41
nn_score_train: false
nn_score_train_interval: 500
noise_rate: 0.0
notes: ''
num_tasks: 0
num_training_examples: 0
order: 3
out_dir: ./models/conjunction/test_san_abad845f
precision: full
prefix_score_bsize: 100
prefix_score_eval: false
prefix_score_n_points: 12
prefix_score_n_repeats: 4
prefix_score_train: false
prefix_score_train_interval: 500
project: in-context-learning
resume_id: ''
save_every_steps: 1000
task: conjunction
task_kwargs: {}
test_run: false
train_steps: 15000
wandb: false
